#! /bin/bash
echo -e "This program copies a file to the /stuff directory.\n"
echo -e "Which file would you like to copy? -->\c"
read FILENAME
mkdir /stuff || echo "The stuff directory could not be created."
cp -f $FILENAME /stuff && echo "$FILENAME was successfully copied to /stuff"

